/** @format */

export default {
	loremIpsum: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc efficitur erat ullamcorper magna sodales, eget tempor justo imperdiet. In suscipit sollicitudin mi, sit amet tincidunt elit sodales eu. Fusce eu tincidunt sapien. Duis aliquam libero mattis, viverra velit vel, vulputate nulla. In ipsum ante, maximus nec posuere in, mollis in orci. In rutrum lectus enim, vel vestibulum massa malesuada et. Aliquam ac tortor est. Ut at mollis erat. Pellentesque ac neque nulla. Nunc elit erat, porta eu eros sit amet, fermentum volutpat ex. Sed feugiat ac ante sed sagittis. Ut vestibulum, mauris ut suscipit efficitur, felis risus fermentum sem, vel volutpat nisl ante et nulla. Nam dapibus mi dignissim velit varius, consequat ultrices arcu dictum.
	
	Praesent congue cursus massa, at maximus purus euismod in. Pellentesque faucibus mauris dignissim turpis hendrerit, id interdum lectus euismod. Donec sit amet bibendum felis, ac lobortis dui. Morbi varius euismod quam, at bibendum felis feugiat eu. Nullam sed est quis nunc viverra laoreet vitae eget leo. Aenean iaculis, odio non tempus aliquam, enim felis hendrerit lacus, nec laoreet neque lectus facilisis nibh. Morbi pharetra enim eget velit placerat, non hendrerit tellus posuere. Aenean eget tempor odio. Curabitur suscipit in nisl eget interdum. Nulla facilisi. Donec id sagittis ex. Aliquam maximus tincidunt tincidunt. Duis eu ante tortor.
	
	In vel tellus turpis. Proin ut diam volutpat, viverra diam in, dignissim ex. Maecenas libero turpis, tempor nec interdum ac, molestie mollis dui. Vestibulum auctor sapien ante, et molestie est tincidunt ac. Donec bibendum tristique ex sed maximus. Curabitur mollis tincidunt dolor vitae accumsan. Etiam vel imperdiet lacus, ac vehicula eros. Maecenas sed ornare justo. Phasellus at diam tempor, malesuada lacus vitae, finibus massa. Proin pretium dolor ac massa suscipit venenatis. Praesent vestibulum nisi et est malesuada malesuada. Cras vel rutrum turpis. Maecenas condimentum eu justo sed euismod. Mauris hendrerit, enim ac interdum accumsan, quam mauris tincidunt eros, id porttitor libero ex sed orci.
	
	Donec urna eros, dapibus ac porta nec, efficitur in arcu. Fusce scelerisque tortor nec suscipit ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus purus in urna imperdiet, non cursus augue congue. Nulla sagittis augue in bibendum vestibulum. Donec at lorem fermentum, convallis massa vel, egestas diam. Maecenas suscipit vel arcu in finibus. Sed laoreet, mauris sit amet tempus lobortis, odio felis convallis odio, finibus accumsan elit diam quis dolor. Maecenas pulvinar vestibulum consectetur. Morbi rutrum odio ut sagittis tristique. Nunc lobortis lacus sit amet faucibus fermentum. Vivamus faucibus justo a turpis consequat fringilla. Etiam at eros sit amet felis vehicula ultricies at tincidunt mi. Ut sapien elit, feugiat sed luctus id, ornare in eros. Proin posuere ipsum a sollicitudin vulputate.
	
	Maecenas quis elit pretium ante porttitor porttitor. Mauris ullamcorper, nisl sit amet eleifend sodales, mauris sapien commodo sem, eu aliquet lectus orci sed sem. Nam scelerisque, risus nec ornare elementum, justo nunc tincidunt odio, sed vestibulum massa ex non lectus. Aliquam sed nunc sit amet ante ultricies tincidunt. In euismod odio tempor, semper turpis sed, condimentum nisi. Nam tristique orci eu nunc efficitur, eget faucibus risus pharetra. Phasellus ultrices porttitor diam et fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse ut diam neque. Vestibulum et volutpat lectus. Vivamus ac porta eros, id mattis nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam eget elementum urna.`
};
